name: TheCanbus

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  build:
    name: Generate, Build & Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install
        run: sudo apt-get install build-essential
      - name: Generate
        run: make
      - name: Build & Test
        run: make check
